version: "3.9"
services:
  app:
    build: ./app/
    ports:
      - 4000:4000
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    networks:
      - project-network
 
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    networks:
      - project-network
    environment:
      POSTGRES_DB: "dbtest"
      POSTGRES_USER: "show"
      POSTGRES_PASSWORD: "1238"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U show -d dbtest"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

networks:
  project-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16 # Подсеть для контейнеров
